apiVersion: v1
kind: Pod
metadata:
  name: apache-pod

spec:
  containers:
  - name: apache-container
    image: nwudofidelis/fidelis-apache:v1.1 # image pulled from DockerHub
    ports:
    - containerPort: 80